/**
  ******************************************************************************
  * file           : example.c
  * brief          : example program body
  ******************************************************************************
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* Includes ------------------------------------------------------------------*/
#include "example.h"
#include "st25dvxxkc.h"
#include "stdio.h"
#include "mx_st25dvxxkc.h"
/* Private typedef -----------------------------------------------------------*/


/* Private define ------------------------------------------------------------*/

/* Private function prototypes -----------------------------------------------*/


/* Private variables */


uint8_t awritedata[16];
uint8_t areaddata[16];
uint8_t cnt = 0;
uint16_t mblength;
st25dvxxkc_mb_ctrl_dyn_status_t mbctrldynstatus;
st25dvxxkc_en_status_e MB_mode;
st25dvxxkc_passwd_t passwd;
st25dvxxkc_i2csso_status_e i2csso;

uint32_t Button_TimeCount;
st25dvxxkc_object_t obj;

/**
  * ########## Step 1 ##########
  * The init of ST25DV is triggered by the applicative code
  * The initialization code is generated by STM32CubeMX2 under the targets folder.
  * All the aliases used here are generated by STM32CubeMX2 under the targets folder: see stm32_mcu_def.h.
  * output: EXEC_STATUS_INIT_OK if OK, EXEC_STATUS_ERROR in case of error
  */

app_status_t app_init(void)
{

  /* Init of the Leds on X-NUCLEO-NFC07A1 board */
  PRINTF("GREEN LED INIT\n");
  PRINTF("BLUE LED INIT\n");
  PRINTF("YELLOW LED INIT\n");

  PRINTF("GREEN LED ON\n");
  HAL_Delay(300);
  PRINTF("BLUE LED ON\n");
  HAL_Delay(300);
  PRINTF("YELLOW LED ON\n");
  HAL_Delay(300);

  /* Init UART for display message on console */

  printf("----------------------------------------");
  printf("\n\r*****Welcome to x-cube-nfc7 example*****");
  printf("\n\r----------------------------------------");

  /* Init ST25DVXXKC driver */
  while (st25dvxxkc_drv_init(&obj, ST25DVXXKC_0) != NFCTAG_OK);

  /* Init done */
  PRINTF("GREEN LED OFF\n");
  HAL_Delay(300);
  PRINTF("BLUE LED OFF\n");
  HAL_Delay(300);
  PRINTF("BLUE LED OFF\n");
  HAL_Delay(300);

  printf("\n\r\n\r This program will show you basic example on how to use the mailbox on I2C side");

  /* If not activated, activate Mailbox, as long as MB is ON EEPROM is not available */
  st25dvxxkc_drv_readmbmode(&obj, &MB_mode);
  if (MB_mode == ST25DVXXKC_DISABLE)
  {
    /* You need to present password before changing static configuration */
    st25dvxxkc_drv_readi2csecuritysession_dyn(&obj, &i2csso);
    if (i2csso == ST25DVXXKC_SESSION_CLOSED)
    {
      /* if I2C session is closed, present password to open session */
      passwd.msbpasswd = 0; /* Default value for password */
      passwd.lsbpasswd = 0; /* change it if password has been modified */
      st25dvxxkc_drv_presenti2cpassword(&obj, passwd);
    }
    st25dvxxkc_drv_writembmode(&obj, ST25DVXXKC_ENABLE);

    /* Close session as dynamic register doesn't need open session for modification */
    passwd.msbpasswd = 123;
    passwd.lsbpasswd = 123;
    st25dvxxkc_drv_presenti2cpassword(&obj, passwd);
  }

  /* Enable Mailbox in dynamique register */
  st25dvxxkc_drv_setmben_dyn(&obj);

  printf("\n\r\n\rMailbox is activated");

  /* prepare data to write */
  for (cnt = 0; cnt < 16; cnt++)
  {
    awritedata[cnt] = cnt;
  }

  /* Check if Mailbox is available */
  st25dvxxkc_drv_readmbctrl_dyn(&obj, &mbctrldynstatus);

  /* If MB is available, write data */
  if ((mbctrldynstatus.hostputmsg == 0) && (mbctrldynstatus.rfputmsg == 0))
  {
    printf("\n\r\n\rMailbox available, write data to it");
    st25dvxxkc_drv_writemailboxdata(&obj, awritedata, 16);
  }

  /* Read length of message */
  st25dvxxkc_drv_readmblength_dyn(&obj, (uint8_t *)&mblength);
  printf("\n\r\n\rLength of data write in MBCTRL register : %d", mblength);
  mblength++;
  printf("\n\rNeed to add 1 to the length as it start at 0 : %d", mblength);
  /* Read mailbox status */
  st25dvxxkc_drv_readmbctrl_dyn(&obj, &mbctrldynstatus);
  printf("\n\r\n\rCtrl MB status register value:");
  printf("\n\rHost(i2c) Missed Message  = %d", mbctrldynstatus.hostmissmsg);
  printf("\n\rRF(reader) Missed Message = %d", mbctrldynstatus.rfmissmsg);
  printf("\n\rHost(i2c) Put Message     = %d", mbctrldynstatus.hostputmsg);
  printf("\n\rRF(reader) Put Message    = %d", mbctrldynstatus.rfputmsg);
  printf("\n\rMailbox Enable            = %d", mbctrldynstatus.mbenable);

  /* Read all data in Mailbox */
  st25dvxxkc_drv_readmailboxdata(&obj, areaddata, 0, mblength);
  printf("\n\r\n\rData read in Mailbox:\n\r");
  /* prepare data to write */
  for (cnt = 0; cnt < 16; cnt++)
  {
    printf("0x%02X ", areaddata[cnt]);
  }

  st25dvxxkc_drv_resetmben_dyn(&obj);
  st25dvxxkc_drv_setmben_dyn(&obj);

  /* Read all data in Mailbox */
  st25dvxxkc_drv_readmailboxdata(&obj, areaddata, 0, mblength);
  printf("\n\r\n\rClear mailbox by de/reactivate it or by reading it with a reader, read data:\n\r");
  /* prepare data to write */
  for (cnt = 0; cnt < 16; cnt++)
  {
    printf("0x%02X ", areaddata[cnt]);
  }

  printf("\n\r\n\r----------------------------------------");
  printf("\n\r*****        end of example        *****");
  printf("\n\r----------------------------------------\n\r\n\r");

  return EXEC_STATUS_INIT_OK;
}

/**
  * ########## Step 2 ##########
  * Run the NFC Application Process.
  * The values are displayed on the terminal.
  * output: EXEC_STATUS_OK if OK, EXEC_STATUS_ERROR in case of error
  */

app_status_t app_process(void)
{

  app_status_t return_status = EXEC_STATUS_OK;

  return return_status;
}

/**
  * ########## Step 3 ##########
  * Deinitializes ST25DV before leaving the scenario.
  * The de-initialization code is generated by STM32CubeMX2 under the targets folder.
  * All the aliases used here are generated by STM32CubeMX2 under the targets folder: see stm32_mcu_def.h.
  * output: EXEC_STATUS_OK if OK, EXEC_STATUS_ERROR in case of error
  */
app_status_t app_deinit(void)
{

  return EXEC_STATUS_OK;
}